### Listar todos os usuários
GET http://localhost:8080/usuarios
Content-Type: application/json

###

### Criar um usuário
POST http://localhost:8080/usuarios
Content-Type: application/json

{
  "nome": "João Silva",
  "cpf": "12345678900",
  "email": "joao@email.com",
  "cargo": "Gerente",
  "login": "joaos",
  "senha": "123456"
}
